export interface CountryDialCode {
  name: string;
  iso2: string;
  dialCode: string;
  flag: string;
}

// Common countries with their international dial codes, sorted alphabetically by name.
export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { name: "Afghanistan", iso2: "AF", dialCode: "+93", flag: "🇦🇫" },
  { name: "Albania", iso2: "AL", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", iso2: "DZ", dialCode: "+213", flag: "🇩🇿" },
  { name: "Argentina", iso2: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Australia", iso2: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Austria", iso2: "AT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Bangladesh", iso2: "BD", dialCode: "+880", flag: "🇧🇩" },
  { name: "Belgium", iso2: "BE", dialCode: "+32", flag: "🇧🇪" },
  { name: "Benin", iso2: "BJ", dialCode: "+229", flag: "🇧🇯" },
  { name: "Botswana", iso2: "BW", dialCode: "+267", flag: "🇧🇼" },
  { name: "Brazil", iso2: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Burkina Faso", iso2: "BF", dialCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", iso2: "BI", dialCode: "+257", flag: "🇧🇮" },
  { name: "Cameroon", iso2: "CM", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", iso2: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Chad", iso2: "TD", dialCode: "+235", flag: "🇹🇩" },
  { name: "Chile", iso2: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "China", iso2: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", iso2: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Congo (DRC)", iso2: "CD", dialCode: "+243", flag: "🇨🇩" },
  { name: "Congo (Republic)", iso2: "CG", dialCode: "+242", flag: "🇨🇬" },
  { name: "Egypt", iso2: "EG", dialCode: "+20", flag: "🇪🇬" },
  { name: "Eritrea", iso2: "ER", dialCode: "+291", flag: "🇪🇷" },
  { name: "Eswatini", iso2: "SZ", dialCode: "+268", flag: "🇸🇿" },
  { name: "Ethiopia", iso2: "ET", dialCode: "+251", flag: "🇪🇹" },
  { name: "Finland", iso2: "FI", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", iso2: "FR", dialCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", iso2: "GA", dialCode: "+241", flag: "🇬🇦" },
  { name: "Gambia", iso2: "GM", dialCode: "+220", flag: "🇬🇲" },
  { name: "Germany", iso2: "DE", dialCode: "+49", flag: "🇩🇪" },
  { name: "Ghana", iso2: "GH", dialCode: "+233", flag: "🇬🇭" },
  { name: "Greece", iso2: "GR", dialCode: "+30", flag: "🇬🇷" },
  { name: "Guinea", iso2: "GN", dialCode: "+224", flag: "🇬🇳" },
  { name: "India", iso2: "IN", dialCode: "+91", flag: "🇮🇳" },
  { name: "Indonesia", iso2: "ID", dialCode: "+62", flag: "🇮🇩" },
  { name: "Iran", iso2: "IR", dialCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", iso2: "IQ", dialCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", iso2: "IE", dialCode: "+353", flag: "🇮🇪" },
  { name: "Israel", iso2: "IL", dialCode: "+972", flag: "🇮🇱" },
  { name: "Italy", iso2: "IT", dialCode: "+39", flag: "🇮🇹" },
  { name: "Ivory Coast", iso2: "CI", dialCode: "+225", flag: "🇨🇮" },
  { name: "Japan", iso2: "JP", dialCode: "+81", flag: "🇯🇵" },
  { name: "Jordan", iso2: "JO", dialCode: "+962", flag: "🇯🇴" },
  { name: "Kenya", iso2: "KE", dialCode: "+254", flag: "🇰🇪" },
  { name: "Kuwait", iso2: "KW", dialCode: "+965", flag: "🇰🇼" },
  { name: "Lebanon", iso2: "LB", dialCode: "+961", flag: "🇱🇧" },
  { name: "Lesotho", iso2: "LS", dialCode: "+266", flag: "🇱🇸" },
  { name: "Liberia", iso2: "LR", dialCode: "+231", flag: "🇱🇷" },
  { name: "Libya", iso2: "LY", dialCode: "+218", flag: "🇱🇾" },
  { name: "Madagascar", iso2: "MG", dialCode: "+261", flag: "🇲🇬" },
  { name: "Malawi", iso2: "MW", dialCode: "+265", flag: "🇲🇼" },
  { name: "Malaysia", iso2: "MY", dialCode: "+60", flag: "🇲🇾" },
  { name: "Mali", iso2: "ML", dialCode: "+223", flag: "🇲🇱" },
  { name: "Mauritania", iso2: "MR", dialCode: "+222", flag: "🇲🇷" },
  { name: "Mauritius", iso2: "MU", dialCode: "+230", flag: "🇲🇺" },
  { name: "Mexico", iso2: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Morocco", iso2: "MA", dialCode: "+212", flag: "🇲🇦" },
  { name: "Mozambique", iso2: "MZ", dialCode: "+258", flag: "🇲🇿" },
  { name: "Namibia", iso2: "NA", dialCode: "+264", flag: "🇳🇦" },
  { name: "Nepal", iso2: "NP", dialCode: "+977", flag: "🇳🇵" },
  { name: "Netherlands", iso2: "NL", dialCode: "+31", flag: "🇳🇱" },
  { name: "New Zealand", iso2: "NZ", dialCode: "+64", flag: "🇳🇿" },
  { name: "Niger", iso2: "NE", dialCode: "+227", flag: "🇳🇪" },
  { name: "Nigeria", iso2: "NG", dialCode: "+234", flag: "🇳🇬" },
  { name: "Norway", iso2: "NO", dialCode: "+47", flag: "🇳🇴" },
  { name: "Oman", iso2: "OM", dialCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", iso2: "PK", dialCode: "+92", flag: "🇵🇰" },
  { name: "Philippines", iso2: "PH", dialCode: "+63", flag: "🇵🇭" },
  { name: "Poland", iso2: "PL", dialCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", iso2: "PT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", iso2: "QA", dialCode: "+974", flag: "🇶🇦" },
  { name: "Russia", iso2: "RU", dialCode: "+7", flag: "🇷🇺" },
  { name: "Rwanda", iso2: "RW", dialCode: "+250", flag: "🇷🇼" },
  { name: "Saudi Arabia", iso2: "SA", dialCode: "+966", flag: "🇸🇦" },
  { name: "Senegal", iso2: "SN", dialCode: "+221", flag: "🇸🇳" },
  { name: "Sierra Leone", iso2: "SL", dialCode: "+232", flag: "🇸🇱" },
  { name: "Singapore", iso2: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Somalia", iso2: "SO", dialCode: "+252", flag: "🇸🇴" },
  { name: "South Africa", iso2: "ZA", dialCode: "+27", flag: "🇿🇦" },
  { name: "South Korea", iso2: "KR", dialCode: "+82", flag: "🇰🇷" },
  { name: "South Sudan", iso2: "SS", dialCode: "+211", flag: "🇸🇸" },
  { name: "Spain", iso2: "ES", dialCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", iso2: "LK", dialCode: "+94", flag: "🇱🇰" },
  { name: "Sudan", iso2: "SD", dialCode: "+249", flag: "🇸🇩" },
  { name: "Sweden", iso2: "SE", dialCode: "+46", flag: "🇸🇪" },
  { name: "Switzerland", iso2: "CH", dialCode: "+41", flag: "🇨🇭" },
  { name: "Tanzania", iso2: "TZ", dialCode: "+255", flag: "🇹🇿" },
  { name: "Thailand", iso2: "TH", dialCode: "+66", flag: "🇹🇭" },
  { name: "Togo", iso2: "TG", dialCode: "+228", flag: "🇹🇬" },
  { name: "Tunisia", iso2: "TN", dialCode: "+216", flag: "🇹🇳" },
  { name: "Turkey", iso2: "TR", dialCode: "+90", flag: "🇹🇷" },
  { name: "Uganda", iso2: "UG", dialCode: "+256", flag: "🇺🇬" },
  { name: "Ukraine", iso2: "UA", dialCode: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", iso2: "AE", dialCode: "+971", flag: "🇦🇪" },
  { name: "United Kingdom", iso2: "GB", dialCode: "+44", flag: "🇬🇧" },
  { name: "United States", iso2: "US", dialCode: "+1", flag: "🇺🇸" },
  { name: "Vietnam", iso2: "VN", dialCode: "+84", flag: "🇻🇳" },
  { name: "Yemen", iso2: "YE", dialCode: "+967", flag: "🇾🇪" },
  { name: "Zambia", iso2: "ZM", dialCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", iso2: "ZW", dialCode: "+263", flag: "🇿🇼" },
];
