-- ============================================================================
-- Capture migration: live-state features not previously in repo
-- Generated 2026-08-12 from production DB (project mocixgnbnuotmdbvikdh)
-- Covers: A-Pay M-Pesa deposits/withdrawals, admin ban/remove, partner/franchise
-- system + cash-at-bank, 10-pair signal expansion, $15-from-total_balance billing.
-- Idempotent: uses IF NOT EXISTS / CREATE OR REPLACE throughout.
-- ============================================================================

-- ---- Enum: add 'franchise' role (must be committed before use) -------------
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'franchise';

-- ---- Schema: A-Pay columns on deposits -------------------------------------
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS method text DEFAULT 'usdt';
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS apay_order_id text;
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS custom_transaction_id text;
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS kes_amount integer;
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS fx_rate numeric;
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS phone_number text;
ALTER TABLE public.deposits ADD COLUMN IF NOT EXISTS apay_status text;
CREATE UNIQUE INDEX IF NOT EXISTS deposits_custom_txn_uidx ON public.deposits(custom_transaction_id) WHERE custom_transaction_id IS NOT NULL;

-- ---- Schema: A-Pay columns on withdrawals ----------------------------------
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS method text DEFAULT 'usdt';
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS apay_order_id text;
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS custom_transaction_id text;
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS kes_amount integer;
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS fx_rate numeric;
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS phone_number text;
ALTER TABLE public.withdrawals ADD COLUMN IF NOT EXISTS apay_status text;
CREATE UNIQUE INDEX IF NOT EXISTS withdrawals_custom_txn_uidx ON public.withdrawals(custom_transaction_id) WHERE custom_transaction_id IS NOT NULL;

-- ---- Schema: ban columns on profiles ---------------------------------------
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS banned boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS ban_reason text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS banned_at timestamptz;

-- ---- Schema: deposits currency check includes MPESA_KES --------------------
ALTER TABLE public.deposits DROP CONSTRAINT IF EXISTS deposits_crypto_currency_check;
ALTER TABLE public.deposits ADD CONSTRAINT deposits_crypto_currency_check CHECK (crypto_currency = ANY (ARRAY['BTC'::text, 'USDT_TRC20'::text, 'USDT_ERC20'::text, 'MPESA_KES'::text]));

-- ---- Schema: partner_float table (cash-at-bank baseline) -------------------
CREATE TABLE IF NOT EXISTS public.partner_float (
  partner_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  opening_float numeric NOT NULL DEFAULT 0,
  float_date timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);
ALTER TABLE public.partner_float ENABLE ROW LEVEL SECURITY;

-- ---- Settings rows for A-Pay (values set in production, placeholders here) --
INSERT INTO public.settings (key, value) VALUES
  ('apay_fx_deposit_rate', '133'),
  ('apay_fx_withdrawal_rate', '128'),
  ('apay_base_url', 'https://pay-crm.com'),
  ('apay_project_id', 'SET_IN_PRODUCTION'),
  ('apay_api_key', 'SET_IN_PRODUCTION')
ON CONFLICT (key) DO NOTHING;


-- ==== FUNCTIONS: A-Pay deposit side ====
CREATE OR REPLACE FUNCTION public._apply_deposit_credit(_deposit_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _dep record; _current_id uuid; _next_referrer uuid; _level int; _rate numeric; _commission numeric; _rates numeric[] := ARRAY[0.10, 0.06, 0.04, 0.03, 0.02, 0.015, 0.01]; BEGIN SELECT * INTO _dep FROM public.deposits WHERE id = _deposit_id FOR UPDATE; IF _dep IS NULL THEN RETURN false; END IF; IF _dep.status <> 'pending' THEN RETURN false; END IF; UPDATE public.deposits SET status = 'approved', processed_at = now() WHERE id = _deposit_id; UPDATE public.profiles SET total_balance = total_balance + _dep.amount_usd WHERE id = _dep.user_id; _current_id := _dep.user_id; FOR _level IN 1..7 LOOP SELECT referred_by INTO _next_referrer FROM public.profiles WHERE id = _current_id; EXIT WHEN _next_referrer IS NULL; _rate := _rates[_level]; _commission := _dep.amount_usd * _rate; UPDATE public.profiles SET total_balance = total_balance + _commission, team_volume = team_volume + _dep.amount_usd WHERE id = _next_referrer; INSERT INTO public.affiliate_commissions (referrer_id, referee_id, deposit_id, level, deposit_amount, commission_rate, commission_amount) VALUES (_next_referrer, _dep.user_id, _deposit_id, _level, _dep.amount_usd, _rate, _commission) ON CONFLICT (deposit_id, level) DO NOTHING; PERFORM public.recalculate_rank(_next_referrer); _current_id := _next_referrer; END LOOP; RETURN true; END; $function$ ;
CREATE OR REPLACE FUNCTION public.approve_deposit(_deposit_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN IF NOT public.is_staff(auth.uid()) THEN RAISE EXCEPTION 'Not authorized'; END IF; IF NOT public._apply_deposit_credit(_deposit_id) THEN RAISE EXCEPTION 'Deposit not found or already processed'; END IF; END; $function$ ;
CREATE OR REPLACE FUNCTION public.process_mpesa_deposit_statuses() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _r record; _j jsonb; _txn text; _st text; _dep_id uuid; BEGIN FOR _r IN SELECT content FROM net._http_response WHERE created > now() - interval '30 minutes' AND content LIKE '%custom_transaction_id%' AND content LIKE '%QMD%' ORDER BY created ASC LOOP BEGIN _j := _r.content::jsonb; EXCEPTION WHEN OTHERS THEN CONTINUE; END; _txn := _j->>'custom_transaction_id'; _st := _j->>'status'; IF _txn IS NULL OR _st IS NULL THEN CONTINUE; END IF; SELECT id INTO _dep_id FROM public.deposits WHERE custom_transaction_id = _txn AND method = 'mpesa' AND status = 'pending'; IF _dep_id IS NULL THEN CONTINUE; END IF; IF _st = 'Success' THEN UPDATE public.deposits SET apay_status = 'Success' WHERE id = _dep_id; PERFORM public._apply_deposit_credit(_dep_id); ELSIF _st IN ('Failed', 'Rejected') THEN UPDATE public.deposits SET status = 'rejected', apay_status = _st, processed_at = now() WHERE id = _dep_id AND status = 'pending'; END IF; END LOOP; END; $function$ ;
CREATE OR REPLACE FUNCTION public.request_mpesa_deposit(_amount_usd numeric, _phone text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _profile_id uuid; _rate numeric; _kes int; _txn text; _deposit_id uuid; _project_id text; _api_key text; _base_url text; BEGIN IF _amount_usd IS NULL OR _amount_usd <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF; IF _phone IS NULL OR _phone !~ '^254[0-9]{9}$' THEN RAISE EXCEPTION 'Phone must be 12 digits starting with 254, e.g. 254712345678'; END IF; SELECT id INTO _profile_id FROM public.profiles WHERE user_id = auth.uid(); IF _profile_id IS NULL THEN RAISE EXCEPTION 'Profile not found'; END IF; SELECT value::numeric INTO _rate FROM public.settings WHERE key = 'apay_fx_deposit_rate'; SELECT value INTO _project_id FROM public.settings WHERE key = 'apay_project_id'; SELECT value INTO _api_key FROM public.settings WHERE key = 'apay_api_key'; SELECT value INTO _base_url FROM public.settings WHERE key = 'apay_base_url'; IF _rate IS NULL OR _project_id IS NULL OR _api_key IS NULL OR _base_url IS NULL THEN RAISE EXCEPTION 'M-Pesa payments are not configured'; END IF; _kes := round(_amount_usd * _rate)::int; _txn := 'QMD' || replace(gen_random_uuid()::text, '-', ''); INSERT INTO public.deposits (user_id, amount_usd, crypto_currency, tx_hash, status, method, kes_amount, fx_rate, phone_number, custom_transaction_id, apay_status) VALUES (_profile_id, _amount_usd, 'MPESA_KES', _txn, 'pending', 'mpesa', _kes, _rate, _phone, _txn, 'Created') RETURNING id INTO _deposit_id; PERFORM net.http_post(url := _base_url || '/Remotes/create-deposit?project_id=' || _project_id, headers := jsonb_build_object('Content-Type', 'application/json', 'apikey', _api_key), body := jsonb_build_object('amount', _kes, 'currency', 'KES', 'payment_system', 'mpesa', 'custom_transaction_id', _txn, 'custom_user_id', _profile_id::text, 'data', jsonb_build_object('phone_number', _phone))); RETURN _deposit_id; END; $function$ ;
CREATE OR REPLACE FUNCTION public.request_mpesa_deposit_statuses() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _d record; _project_id text; _api_key text; _base_url text; BEGIN SELECT value INTO _project_id FROM public.settings WHERE key = 'apay_project_id'; SELECT value INTO _api_key FROM public.settings WHERE key = 'apay_api_key'; SELECT value INTO _base_url FROM public.settings WHERE key = 'apay_base_url'; IF _project_id IS NULL OR _api_key IS NULL OR _base_url IS NULL THEN RETURN; END IF; UPDATE public.deposits SET status = 'rejected', apay_status = 'Expired', processed_at = now() WHERE method = 'mpesa' AND status = 'pending' AND created_at < now() - interval '24 hours'; FOR _d IN SELECT custom_transaction_id FROM public.deposits WHERE method = 'mpesa' AND status = 'pending' AND custom_transaction_id IS NOT NULL LOOP PERFORM net.http_get(url := _base_url || '/Remotes/deposit-info?project_id=' || _project_id || '&custom_transaction_id=' || _d.custom_transaction_id, headers := jsonb_build_object('apikey', _api_key)); END LOOP; END; $function$ ;

-- ==== FUNCTIONS: A-Pay withdrawal side ====
CREATE OR REPLACE FUNCTION public.approve_withdrawal(_id uuid, _notes text DEFAULT NULL::text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _w record; _project_id text; _api_key text; _base_url text; BEGIN IF NOT public.is_staff(auth.uid()) THEN RAISE EXCEPTION 'Not authorized'; END IF; SELECT * INTO _w FROM public.withdrawals WHERE id = _id FOR UPDATE; IF _w IS NULL THEN RAISE EXCEPTION 'Withdrawal not found'; END IF; IF _w.status <> 'pending' THEN RAISE EXCEPTION 'Only pending withdrawals can be approved'; END IF; UPDATE public.withdrawals SET status='approved', admin_notes=COALESCE(_notes, admin_notes), processed_at=now() WHERE id=_id; IF _w.method = 'mpesa' THEN SELECT value INTO _project_id FROM public.settings WHERE key = 'apay_project_id'; SELECT value INTO _api_key FROM public.settings WHERE key = 'apay_api_key'; SELECT value INTO _base_url FROM public.settings WHERE key = 'apay_base_url'; IF _project_id IS NULL OR _api_key IS NULL OR _base_url IS NULL THEN RAISE EXCEPTION 'M-Pesa payout not configured'; END IF; PERFORM net.http_post(url := _base_url || '/Remotes/create-withdrawal?project_id=' || _project_id, headers := jsonb_build_object('Content-Type', 'application/json', 'apikey', _api_key), body := jsonb_build_object('amount', _w.kes_amount::int, 'currency', 'KES', 'payment_system', 'mpesa', 'custom_transaction_id', _w.custom_transaction_id, 'custom_user_id', _w.user_id::text, 'data', jsonb_build_object('phone_number', _w.phone_number))); UPDATE public.withdrawals SET apay_status = 'Sent' WHERE id = _id; END IF; END; $function$ ;
CREATE OR REPLACE FUNCTION public.process_mpesa_withdrawal_statuses() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _r record; _j jsonb; _txn text; _st text; _w record; BEGIN FOR _r IN SELECT content FROM net._http_response WHERE created > now() - interval '30 minutes' AND content LIKE '%custom_transaction_id%' AND content LIKE '%QMW%' ORDER BY created ASC LOOP BEGIN _j := _r.content::jsonb; EXCEPTION WHEN OTHERS THEN CONTINUE; END; _txn := _j->>'custom_transaction_id'; _st := _j->>'status'; IF _txn IS NULL OR _st IS NULL THEN CONTINUE; END IF; SELECT * INTO _w FROM public.withdrawals WHERE custom_transaction_id = _txn AND method = 'mpesa' AND status = 'approved' FOR UPDATE; IF _w IS NULL THEN CONTINUE; END IF; IF _st = 'Success' THEN UPDATE public.withdrawals SET status = 'completed', apay_status = 'Success', processed_at = now() WHERE id = _w.id; ELSIF _st IN ('Failed', 'Rejected') THEN UPDATE public.profiles SET withdrawable_balance = withdrawable_balance + _w.amount, total_balance = total_balance + _w.amount WHERE id = _w.user_id; UPDATE public.withdrawals SET status = 'rejected', apay_status = _st, admin_notes = COALESCE(admin_notes || ' | ', '') || 'M-Pesa payout ' || lower(_st) || ' - amount refunded', processed_at = now() WHERE id = _w.id; END IF; END LOOP; END; $function$ ;
CREATE OR REPLACE FUNCTION public.reject_withdrawal(_id uuid, _notes text DEFAULT NULL::text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _w record; BEGIN IF NOT public.is_staff(auth.uid()) THEN RAISE EXCEPTION 'Not authorized'; END IF; SELECT * INTO _w FROM public.withdrawals WHERE id = _id FOR UPDATE; IF _w IS NULL THEN RAISE EXCEPTION 'Withdrawal not found'; END IF; IF _w.status <> 'pending' THEN RAISE EXCEPTION 'Only pending withdrawals can be rejected'; END IF; UPDATE public.profiles SET withdrawable_balance = withdrawable_balance + _w.amount, total_balance = total_balance + _w.amount WHERE id = _w.user_id; UPDATE public.withdrawals SET status='rejected', admin_notes=COALESCE(_notes, admin_notes), processed_at=now() WHERE id=_id; END; $function$ ;
CREATE OR REPLACE FUNCTION public.request_mpesa_withdrawal(_amount_usd numeric, _phone text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _profile_id uuid; _withdrawable numeric; _fee numeric; _net numeric; _id uuid; _kyc_approved boolean; _last_requested_at timestamptz; _rate numeric; _kes int; _txn text; BEGIN IF _amount_usd IS NULL OR _amount_usd <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF; IF _amount_usd < 200 THEN RAISE EXCEPTION 'Minimum withdrawal is $200'; END IF; IF _phone IS NULL OR _phone !~ '^254[0-9]{9}$' THEN RAISE EXCEPTION 'Phone must be 12 digits starting with 254, e.g. 254712345678'; END IF; SELECT id, withdrawable_balance INTO _profile_id, _withdrawable FROM public.profiles WHERE user_id = auth.uid() FOR UPDATE; IF _profile_id IS NULL THEN RAISE EXCEPTION 'Profile not found'; END IF; SELECT max(requested_at) INTO _last_requested_at FROM public.withdrawals WHERE user_id = _profile_id AND status <> 'rejected'; IF _last_requested_at IS NOT NULL AND _last_requested_at > now() - interval '14 days' THEN RAISE EXCEPTION 'You can only request a withdrawal once every 14 days. Next available: %', (_last_requested_at + interval '14 days')::date; END IF; SELECT EXISTS (SELECT 1 FROM public.kyc_verifications WHERE user_id = _profile_id AND status = 'approved') INTO _kyc_approved; IF NOT _kyc_approved THEN RAISE EXCEPTION 'KYC_REQUIRED: Please upload a copy of your ID to verify your identity before withdrawing.'; END IF; IF _amount_usd > _withdrawable THEN RAISE EXCEPTION 'Amount exceeds withdrawable profits ($%)', _withdrawable; END IF; SELECT value::numeric INTO _rate FROM public.settings WHERE key = 'apay_fx_withdrawal_rate'; IF _rate IS NULL THEN RAISE EXCEPTION 'M-Pesa withdrawals are not configured'; END IF; _fee := round((_amount_usd * 0.20)::numeric, 2); _net := _amount_usd - _fee; _kes := round(_net * _rate)::int; _txn := 'QMW' || replace(gen_random_uuid()::text, '-', ''); PERFORM set_config('app.bypass_balance_check', 'true', true); UPDATE public.profiles SET withdrawable_balance = withdrawable_balance - _amount_usd, total_balance = total_balance - _amount_usd WHERE id = _profile_id; INSERT INTO public.withdrawals (user_id, amount, wallet_address, status, fee_amount, net_amount, method, kes_amount, fx_rate, phone_number, custom_transaction_id) VALUES (_profile_id, _amount_usd, 'MPESA:' || _phone, 'pending', _fee, _net, 'mpesa', _kes, _rate, _phone, _txn) RETURNING id INTO _id; RETURN _id; END; $function$ ;
CREATE OR REPLACE FUNCTION public.request_mpesa_withdrawal_statuses() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _w record; _project_id text; _api_key text; _base_url text; BEGIN SELECT value INTO _project_id FROM public.settings WHERE key = 'apay_project_id'; SELECT value INTO _api_key FROM public.settings WHERE key = 'apay_api_key'; SELECT value INTO _base_url FROM public.settings WHERE key = 'apay_base_url'; IF _project_id IS NULL OR _api_key IS NULL OR _base_url IS NULL THEN RETURN; END IF; FOR _w IN SELECT custom_transaction_id FROM public.withdrawals WHERE method = 'mpesa' AND status = 'approved' AND custom_transaction_id IS NOT NULL AND processed_at > now() - interval '7 days' LOOP PERFORM net.http_get(url := _base_url || '/Remotes/withdrawal-info?project_id=' || _project_id || '&custom_transaction_id=' || _w.custom_transaction_id, headers := jsonb_build_object('apikey', _api_key)); END LOOP; END; $function$ ;

-- ==== FUNCTIONS: ban/remove + take_signal ====
CREATE OR REPLACE FUNCTION public.admin_delete_user(_target_profile_id uuid) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _target_user uuid; _refs int; _deposits int; _withdrawals int; _takes int; _commissions int; _balance numeric; BEGIN IF NOT public.has_role(auth.uid(), 'admin') THEN RAISE EXCEPTION 'Only admins can remove users'; END IF; SELECT user_id, total_balance INTO _target_user, _balance FROM public.profiles WHERE id = _target_profile_id; IF _target_user IS NULL THEN RAISE EXCEPTION 'User not found'; END IF; IF public.has_role(_target_user, 'admin') THEN RAISE EXCEPTION 'Cannot delete an admin'; END IF; SELECT count(*) INTO _refs FROM public.profiles WHERE referred_by = _target_profile_id; SELECT count(*) INTO _deposits FROM public.deposits WHERE user_id = _target_profile_id AND status = 'approved'; SELECT count(*) INTO _withdrawals FROM public.withdrawals WHERE user_id = _target_profile_id; SELECT count(*) INTO _takes FROM public.signal_takes WHERE user_id = _target_profile_id; SELECT count(*) INTO _commissions FROM public.affiliate_commissions WHERE referrer_id = _target_profile_id OR referee_id = _target_profile_id; IF _refs > 0 OR _deposits > 0 OR _withdrawals > 0 OR _commissions > 0 OR COALESCE(_balance,0) > 0 THEN RAISE EXCEPTION 'Cannot hard-delete: user has % downline referrals, % approved deposits, % withdrawals, % commission records, $% balance. Ban the user instead to preserve financial and referral records.', _refs, _deposits, _withdrawals, _commissions, COALESCE(_balance,0); END IF; DELETE FROM public.signal_takes WHERE user_id = _target_profile_id; DELETE FROM public.deposits WHERE user_id = _target_profile_id; DELETE FROM public.kyc_verifications WHERE user_id = _target_profile_id; DELETE FROM public.subscriptions WHERE user_id = _target_profile_id; DELETE FROM public.subscription_transactions WHERE user_id = _target_profile_id; DELETE FROM public.user_roles WHERE user_id = _target_user; DELETE FROM public.profiles WHERE id = _target_profile_id; DELETE FROM auth.users WHERE id = _target_user; RETURN 'deleted'; END; $function$ ;
CREATE OR REPLACE FUNCTION public.assert_not_banned(_profile_id uuid) RETURNS void LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _banned boolean; BEGIN SELECT banned INTO _banned FROM public.profiles WHERE id = _profile_id; IF _banned THEN RAISE EXCEPTION 'Your account has been suspended. Please contact support.'; END IF; END; $function$ ;
CREATE OR REPLACE FUNCTION public.set_user_banned(_target_profile_id uuid, _banned boolean, _reason text DEFAULT NULL::text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _target_user uuid; BEGIN IF NOT public.has_role(auth.uid(), 'admin') THEN RAISE EXCEPTION 'Only admins can ban users'; END IF; SELECT user_id INTO _target_user FROM public.profiles WHERE id = _target_profile_id; IF _target_user IS NULL THEN RAISE EXCEPTION 'User not found'; END IF; IF public.has_role(_target_user, 'admin') THEN RAISE EXCEPTION 'Cannot ban an admin'; END IF; PERFORM set_config('app.bypass_balance_check', 'true', true); UPDATE public.profiles SET banned = _banned, ban_reason = CASE WHEN _banned THEN _reason ELSE NULL END, banned_at = CASE WHEN _banned THEN now() ELSE NULL END WHERE id = _target_profile_id; END; $function$ ;
CREATE OR REPLACE FUNCTION public.take_signal(_signal_id uuid, _stake numeric) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _profile_id uuid; _balance numeric; _status text; _closes timestamptz; _take_id uuid; _existing uuid; _daily_limit int; _taken_today int; _banned boolean; BEGIN IF _stake <= 0 THEN RAISE EXCEPTION 'Stake must be positive'; END IF; SELECT id, total_balance, banned INTO _profile_id, _balance, _banned FROM public.profiles WHERE user_id = auth.uid() FOR UPDATE; IF _profile_id IS NULL THEN RAISE EXCEPTION 'Profile not found'; END IF; IF _banned THEN RAISE EXCEPTION 'Your account has been suspended. Please contact support.'; END IF; IF _balance < 200 THEN RAISE EXCEPTION 'You need at least $200 in your account balance to take signals. Please make a deposit to start trading.'; END IF; SELECT status, closes_at INTO _status, _closes FROM public.signals WHERE id = _signal_id FOR UPDATE; IF _status IS NULL THEN RAISE EXCEPTION 'Signal not found'; END IF; IF _status <> 'open' THEN RAISE EXCEPTION 'Signal is no longer open'; END IF; IF _closes <= now() THEN RAISE EXCEPTION 'Signal take window has closed'; END IF; SELECT id INTO _existing FROM public.signal_takes WHERE user_id = _profile_id AND signal_id = _signal_id; IF _existing IS NOT NULL THEN RAISE EXCEPTION 'You have already taken this signal'; END IF; _daily_limit := public.get_daily_signal_limit(_profile_id); SELECT count(*) INTO _taken_today FROM public.signal_takes WHERE user_id = _profile_id AND created_at >= public.start_of_eat_day(); IF _taken_today >= _daily_limit THEN RAISE EXCEPTION 'Daily signal limit reached (%/% signals). Refer more users to unlock additional signals per day.', _taken_today, _daily_limit; END IF; IF _balance < _stake THEN RAISE EXCEPTION 'Insufficient balance'; END IF; PERFORM set_config('app.bypass_balance_check', 'true', true); UPDATE public.profiles SET total_balance = total_balance - _stake WHERE id = _profile_id; INSERT INTO public.signal_takes (user_id, signal_id, stake_amount) VALUES (_profile_id, _signal_id, _stake) RETURNING id INTO _take_id; RETURN _take_id; END; $function$ ;

-- ==== FUNCTIONS: partner/franchise core ====
CREATE OR REPLACE FUNCTION public.cash_at_bank_for(_partner_id uuid) RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT COALESCE((SELECT opening_float FROM public.partner_float WHERE partner_id = _partner_id), 0) + COALESCE((SELECT sum(d.amount_usd) FROM public.deposits d WHERE d.status='approved' AND d.user_id IN (SELECT profile_id FROM public.downline_ids_of(_partner_id)) AND d.created_at > COALESCE((SELECT float_date FROM public.partner_float WHERE partner_id = _partner_id), '-infinity'::timestamptz)), 0) - COALESCE((SELECT sum(w.amount) FROM public.withdrawals w WHERE w.status IN ('approved','completed') AND w.user_id IN (SELECT profile_id FROM public.downline_ids_of(_partner_id)) AND w.requested_at > COALESCE((SELECT float_date FROM public.partner_float WHERE partner_id = _partner_id), '-infinity'::timestamptz)), 0); $function$ ;
CREATE OR REPLACE FUNCTION public.downline_ids_of(_root uuid) RETURNS TABLE(profile_id uuid) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ WITH RECURSIVE tree AS (SELECT p.id, 1 AS depth FROM public.profiles p WHERE p.referred_by = _root UNION ALL SELECT c.id, t.depth + 1 FROM public.profiles c JOIN tree t ON c.referred_by = t.id WHERE t.depth < 7) SELECT id FROM tree; $function$ ;
CREATE OR REPLACE FUNCTION public.franchise_guard() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT public.has_role(auth.uid(), 'franchise') OR public.has_role(auth.uid(), 'admin'); $function$ ;
CREATE OR REPLACE FUNCTION public.is_franchise(_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT public.has_role(_user_id, 'franchise'); $function$ ;
CREATE OR REPLACE FUNCTION public.my_downline_ids() RETURNS TABLE(profile_id uuid) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT public.downline_ids_of((SELECT id FROM public.profiles WHERE user_id = auth.uid())); $function$ ;
CREATE OR REPLACE FUNCTION public.set_user_role(_target_user_id uuid, _role text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN IF NOT public.has_role(auth.uid(), 'admin') THEN RAISE EXCEPTION 'Not authorized'; END IF; IF _role NOT IN ('user', 'moderator', 'admin', 'franchise') THEN RAISE EXCEPTION 'Invalid role'; END IF; DELETE FROM public.user_roles WHERE user_id = _target_user_id; IF _role <> 'user' THEN INSERT INTO public.user_roles (user_id, role) VALUES (_target_user_id, _role::app_role); END IF; END; $function$ ;

-- ==== FUNCTIONS: partner scoped read RPCs ====
CREATE OR REPLACE FUNCTION public.franchise_get_deposits() RETURNS TABLE(id uuid, member_name text, amount_usd numeric, method text, status text, created_at timestamp with time zone, processed_at timestamp with time zone) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT d.id, p.full_name, d.amount_usd, d.method, d.status, d.created_at, d.processed_at FROM public.deposits d JOIN public.profiles p ON p.id = d.user_id WHERE public.franchise_guard() AND d.user_id IN (SELECT profile_id FROM public.my_downline_ids()) ORDER BY d.created_at DESC; $function$ ;
CREATE OR REPLACE FUNCTION public.franchise_get_members() RETURNS TABLE(id uuid, full_name text, current_rank text, total_balance numeric, total_earnings numeric, total_withdrawn numeric, team_volume numeric, banned boolean, created_at timestamp with time zone) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT p.id, p.full_name, p.current_rank, p.total_balance, p.total_earnings, p.total_withdrawn, p.team_volume, p.banned, p.created_at FROM public.profiles p WHERE public.franchise_guard() AND p.id IN (SELECT profile_id FROM public.my_downline_ids()) ORDER BY p.created_at DESC; $function$ ;
CREATE OR REPLACE FUNCTION public.franchise_get_stats() RETURNS TABLE(total_members integer, total_deposits numeric, total_withdrawals numeric, total_commissions numeric, total_team_balance numeric, cash_at_bank numeric) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT (SELECT count(*)::int FROM public.my_downline_ids()), COALESCE((SELECT sum(d.amount_usd) FROM public.deposits d WHERE d.status='approved' AND d.user_id IN (SELECT profile_id FROM public.my_downline_ids())),0), COALESCE((SELECT sum(w.amount) FROM public.withdrawals w WHERE w.status IN ('approved','completed') AND w.user_id IN (SELECT profile_id FROM public.my_downline_ids())),0), COALESCE((SELECT sum(ac.commission_amount) FROM public.affiliate_commissions ac WHERE ac.referrer_id IN (SELECT profile_id FROM public.my_downline_ids())),0) + COALESCE((SELECT sum(psc.commission_amount) FROM public.profit_share_commissions psc WHERE psc.referrer_id IN (SELECT profile_id FROM public.my_downline_ids())),0), COALESCE((SELECT sum(p.total_balance) FROM public.profiles p WHERE p.id IN (SELECT profile_id FROM public.my_downline_ids())),0), public.cash_at_bank_for((SELECT id FROM public.profiles WHERE user_id = auth.uid())) WHERE public.franchise_guard(); $function$ ;
CREATE OR REPLACE FUNCTION public.franchise_get_withdrawals() RETURNS TABLE(id uuid, member_name text, amount numeric, net_amount numeric, method text, status text, requested_at timestamp with time zone, processed_at timestamp with time zone) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT w.id, p.full_name, w.amount, w.net_amount, w.method, w.status, w.requested_at, w.processed_at FROM public.withdrawals w JOIN public.profiles p ON p.id = w.user_id WHERE public.franchise_guard() AND w.user_id IN (SELECT profile_id FROM public.my_downline_ids()) ORDER BY w.requested_at DESC; $function$ ;

-- ==== FUNCTIONS: admin view-as + float setter ====
CREATE OR REPLACE FUNCTION public.admin_franchise_deposits(_franchise_id uuid) RETURNS TABLE(id uuid, member_name text, amount_usd numeric, method text, status text, created_at timestamp with time zone, processed_at timestamp with time zone) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT d.id, p.full_name, d.amount_usd, d.method, d.status, d.created_at, d.processed_at FROM public.deposits d JOIN public.profiles p ON p.id = d.user_id WHERE public.has_role(auth.uid(),'admin') AND d.user_id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id)) ORDER BY d.created_at DESC; $function$ ;
CREATE OR REPLACE FUNCTION public.admin_franchise_members(_franchise_id uuid) RETURNS TABLE(id uuid, full_name text, current_rank text, total_balance numeric, total_earnings numeric, total_withdrawn numeric, team_volume numeric, banned boolean, created_at timestamp with time zone) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT p.id, p.full_name, p.current_rank, p.total_balance, p.total_earnings, p.total_withdrawn, p.team_volume, p.banned, p.created_at FROM public.profiles p WHERE public.has_role(auth.uid(),'admin') AND p.id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id)) ORDER BY p.created_at DESC; $function$ ;
CREATE OR REPLACE FUNCTION public.admin_franchise_stats(_franchise_id uuid) RETURNS TABLE(total_members integer, total_deposits numeric, total_withdrawals numeric, total_commissions numeric, total_team_balance numeric, cash_at_bank numeric) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT (SELECT count(*)::int FROM public.downline_ids_of(_franchise_id)), COALESCE((SELECT sum(d.amount_usd) FROM public.deposits d WHERE d.status='approved' AND d.user_id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id))),0), COALESCE((SELECT sum(w.amount) FROM public.withdrawals w WHERE w.status IN ('approved','completed') AND w.user_id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id))),0), COALESCE((SELECT sum(ac.commission_amount) FROM public.affiliate_commissions ac WHERE ac.referrer_id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id))),0) + COALESCE((SELECT sum(psc.commission_amount) FROM public.profit_share_commissions psc WHERE psc.referrer_id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id))),0), COALESCE((SELECT sum(p.total_balance) FROM public.profiles p WHERE p.id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id))),0), public.cash_at_bank_for(_franchise_id) WHERE public.has_role(auth.uid(),'admin'); $function$ ;
CREATE OR REPLACE FUNCTION public.admin_franchise_withdrawals(_franchise_id uuid) RETURNS TABLE(id uuid, member_name text, amount numeric, net_amount numeric, method text, status text, requested_at timestamp with time zone, processed_at timestamp with time zone) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT w.id, p.full_name, w.amount, w.net_amount, w.method, w.status, w.requested_at, w.processed_at FROM public.withdrawals w JOIN public.profiles p ON p.id = w.user_id WHERE public.has_role(auth.uid(),'admin') AND w.user_id IN (SELECT profile_id FROM public.downline_ids_of(_franchise_id)) ORDER BY w.requested_at DESC; $function$ ;
CREATE OR REPLACE FUNCTION public.admin_list_franchises() RETURNS TABLE(profile_id uuid, full_name text, email text) LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$ SELECT p.id, p.full_name, p.email FROM public.profiles p JOIN public.user_roles ur ON ur.user_id = p.user_id WHERE ur.role = 'franchise' AND public.has_role(auth.uid(),'admin') ORDER BY p.full_name; $function$ ;
CREATE OR REPLACE FUNCTION public.set_partner_float(_partner_id uuid, _opening_float numeric) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _me uuid; BEGIN IF NOT public.has_role(auth.uid(),'admin') THEN RAISE EXCEPTION 'Only admins can set partner float'; END IF; SELECT id INTO _me FROM public.profiles WHERE user_id = auth.uid(); INSERT INTO public.partner_float (partner_id, opening_float, float_date, updated_at, updated_by) VALUES (_partner_id, _opening_float, now(), now(), _me) ON CONFLICT (partner_id) DO UPDATE SET opening_float = EXCLUDED.opening_float, float_date = now(), updated_at = now(), updated_by = _me; END; $function$ ;

-- ==== FUNCTIONS: signal engine (10-pair) + market + subscription ====
CREATE OR REPLACE FUNCTION public.generate_signal(_force boolean DEFAULT false) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE v_open_exists boolean; v_hour int; v_slot int; v_doy int; v_idx int; v_pair text; v_direction text; v_fallback_price numeric; v_cached_price numeric; v_entry numeric; v_target numeric; v_stop numeric; v_message text; v_pairs text[] := ARRAY['BTC/USDT','EUR/USD','SOL/USDT','GBP/USD','BNB/USDT','DOGE/USDT','USD/JPY','USD/CHF','EUR/GBP','EUR/JPY']; v_dirs text[] := ARRAY['LONG','SHORT','LONG','SHORT','LONG','SHORT','LONG','SHORT','SHORT','LONG']; v_fallbacks numeric[] := ARRAY[95000,1.09,220,1.27,680,0.4,149,0.88,0.84,162]; v_templates text[] := ARRAY['%s momentum building. Clean %s setup forming.','%s breakout confirmed - taking a %s position.','%s RSI divergence, going %s for a quick scalp.','%s volume spike detected. %s signal active.','%s retesting key level - %s entry triggered.']; BEGIN IF NOT _force THEN SELECT EXISTS (SELECT 1 FROM public.signals WHERE status = 'open' AND closes_at > now()) INTO v_open_exists; IF v_open_exists THEN RETURN; END IF; END IF; v_hour := EXTRACT(HOUR FROM (now() AT TIME ZONE 'Africa/Nairobi'))::int; v_slot := (v_hour / 4) % 6; v_doy := EXTRACT(DOY FROM (now() AT TIME ZONE 'Africa/Nairobi'))::int; v_idx := ((v_doy * 6 + v_slot) % 10) + 1; v_pair := v_pairs[v_idx]; v_direction := v_dirs[v_idx]; v_fallback_price := v_fallbacks[v_idx]; SELECT price INTO v_cached_price FROM public.market_prices WHERE pair = v_pair AND updated_at > now() - interval '30 minutes'; v_entry := COALESCE(v_cached_price, v_fallback_price) * (1 + (random() - 0.5) * 0.004); IF v_direction = 'LONG' THEN v_target := v_entry * 1.012; v_stop := v_entry * 0.994; ELSE v_target := v_entry * 0.988; v_stop := v_entry * 1.006; END IF; v_message := format(v_templates[1 + floor(random() * array_length(v_templates, 1))::int], v_pair, lower(v_direction)); INSERT INTO public.signals (pair, direction, entry_price, target_price, stop_loss, profit_percentage, message, status, closes_at) VALUES (v_pair, v_direction, v_entry, v_target, v_stop, 1.2, v_message, 'open', now() + interval '5 minutes'); END; $function$ ;
CREATE OR REPLACE FUNCTION public.process_market_prices() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE v_crypto_body jsonb; v_forex_body jsonb; v_eur numeric; v_gbp numeric; v_jpy numeric; v_chf numeric; BEGIN SELECT content::jsonb INTO v_crypto_body FROM net._http_response WHERE status_code = 200 AND content LIKE '%bitcoin%' ORDER BY created DESC LIMIT 1; SELECT content::jsonb INTO v_forex_body FROM net._http_response WHERE status_code = 200 AND content LIKE '%rates%' ORDER BY created DESC LIMIT 1; IF v_crypto_body IS NOT NULL THEN INSERT INTO public.market_prices (pair, price, updated_at) VALUES ('BTC/USDT', (v_crypto_body->'bitcoin'->>'usd')::numeric, now()), ('SOL/USDT', (v_crypto_body->'solana'->>'usd')::numeric, now()), ('BNB/USDT', (v_crypto_body->'binancecoin'->>'usd')::numeric, now()), ('DOGE/USDT', (v_crypto_body->'dogecoin'->>'usd')::numeric, now()) ON CONFLICT (pair) DO UPDATE SET price = EXCLUDED.price, updated_at = EXCLUDED.updated_at; END IF; IF v_forex_body IS NOT NULL THEN v_eur := (v_forex_body->'rates'->>'EUR')::numeric; v_gbp := (v_forex_body->'rates'->>'GBP')::numeric; v_jpy := (v_forex_body->'rates'->>'JPY')::numeric; v_chf := (v_forex_body->'rates'->>'CHF')::numeric; INSERT INTO public.market_prices (pair, price, updated_at) VALUES ('EUR/USD', 1 / v_eur, now()), ('GBP/USD', 1 / v_gbp, now()), ('USD/JPY', v_jpy, now()), ('USD/CHF', v_chf, now()), ('EUR/GBP', v_gbp / v_eur, now()), ('EUR/JPY', v_jpy / v_eur, now()) ON CONFLICT (pair) DO UPDATE SET price = EXCLUDED.price, updated_at = EXCLUDED.updated_at; END IF; DELETE FROM net._http_response WHERE created < now() - interval '1 day'; END; $function$ ;
CREATE OR REPLACE FUNCTION public.process_subscription_billing(_profile_id uuid, _manual boolean DEFAULT false) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ DECLARE _sub record; _balance numeric; _new_period_start timestamptz; _new_period_end timestamptz; BEGIN SELECT * INTO _sub FROM public.subscriptions WHERE user_id = _profile_id FOR UPDATE; IF _sub IS NULL THEN INSERT INTO public.subscriptions (user_id, status, started_at, current_period_start, current_period_end, auto_renew) VALUES (_profile_id, 'active', now(), now(), now() + interval '30 days', true) RETURNING * INTO _sub; END IF; IF now() < _sub.current_period_end THEN RETURN 'not_due'; END IF; IF _sub.status = 'expired' AND NOT _manual AND NOT _sub.auto_renew THEN RETURN 'skipped_no_autorenew'; END IF; SELECT total_balance INTO _balance FROM public.profiles WHERE id = _profile_id FOR UPDATE; IF _balance >= 15 THEN PERFORM set_config('app.bypass_balance_check', 'true', true); UPDATE public.profiles SET total_balance = total_balance - 15 WHERE id = _profile_id; _new_period_start := GREATEST(_sub.current_period_end, now()); _new_period_end := _new_period_start + interval '30 days'; UPDATE public.subscriptions SET status = 'active', current_period_start = _new_period_start, current_period_end = _new_period_end, updated_at = now() WHERE user_id = _profile_id; INSERT INTO public.subscription_transactions (user_id, amount, previous_available_balance, new_available_balance, period_start, period_end, status) VALUES (_profile_id, 15, _balance, _balance - 15, _new_period_start, _new_period_end, 'success'); RETURN 'success'; ELSE UPDATE public.subscriptions SET status = 'expired', updated_at = now() WHERE user_id = _profile_id; INSERT INTO public.subscription_transactions (user_id, amount, previous_available_balance, new_available_balance, period_start, period_end, status) VALUES (_profile_id, 15, _balance, _balance, _sub.current_period_start, _sub.current_period_end, 'failed'); RETURN 'failed_insufficient_balance'; END IF; END; $function$ ;
CREATE OR REPLACE FUNCTION public.request_market_prices() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$ BEGIN PERFORM net.http_get('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,solana,binancecoin,dogecoin&vs_currencies=usd'); PERFORM net.http_get('https://api.frankfurter.app/latest?from=USD&to=EUR,GBP,JPY,CHF'); END; $function$ ;

-- ============================================================================
-- GRANTs for the captured functions
-- ============================================================================
GRANT EXECUTE ON FUNCTION public.request_mpesa_deposit(numeric, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_mpesa_withdrawal(numeric, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_user_banned(uuid, boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_user_role(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_downline_ids() TO authenticated;
GRANT EXECUTE ON FUNCTION public.franchise_get_members() TO authenticated;
GRANT EXECUTE ON FUNCTION public.franchise_get_deposits() TO authenticated;
GRANT EXECUTE ON FUNCTION public.franchise_get_withdrawals() TO authenticated;
GRANT EXECUTE ON FUNCTION public.franchise_get_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_franchise_members(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_franchise_deposits(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_franchise_withdrawals(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_franchise_stats(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_franchises() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_partner_float(uuid, numeric) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.request_mpesa_deposit_statuses() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.process_mpesa_deposit_statuses() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.request_mpesa_withdrawal_statuses() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.process_mpesa_withdrawal_statuses() FROM PUBLIC, anon, authenticated;

-- ============================================================================
-- Cron schedule (captured from production). Unschedule-then-schedule = idempotent.
-- ============================================================================
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'mpesa-deposit-poll-request';
SELECT cron.schedule('mpesa-deposit-poll-request', '*/2 * * * *', $$SELECT public.request_mpesa_deposit_statuses();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'mpesa-deposit-poll-process';
SELECT cron.schedule('mpesa-deposit-poll-process', '1-59/2 * * * *', $$SELECT public.process_mpesa_deposit_statuses();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'mpesa-withdrawal-poll-request';
SELECT cron.schedule('mpesa-withdrawal-poll-request', '*/2 * * * *', $$SELECT public.request_mpesa_withdrawal_statuses();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'mpesa-withdrawal-poll-process';
SELECT cron.schedule('mpesa-withdrawal-poll-process', '1-59/2 * * * *', $$SELECT public.process_mpesa_withdrawal_statuses();$$);
-- Signal, market-price, subscription, close jobs (already existed; re-asserted for completeness)
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'generate-signal-schedule';
SELECT cron.schedule('generate-signal-schedule', '0 23,3,7,11,15,19 * * *', $$SELECT public.generate_signal();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'close-signals-schedule';
SELECT cron.schedule('close-signals-schedule', '* * * * *', $$SELECT public.close_due_signals();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'request-market-prices-schedule';
SELECT cron.schedule('request-market-prices-schedule', '*/5 * * * *', $$SELECT public.request_market_prices();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'process-market-prices-schedule';
SELECT cron.schedule('process-market-prices-schedule', '1,6,11,16,21,26,31,36,41,46,51,56 * * * *', $$SELECT public.process_market_prices();$$);
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'process-subscriptions-schedule';
SELECT cron.schedule('process-subscriptions-schedule', '0 * * * *', $$SELECT public.process_all_subscriptions();$$);
